### ISSUE TITLE
Failure to read code from v1.x Microbit

### ISSUE THREAD

**Issue by kingsfleet** [carlosperate/ubittool#14]
Seen this problem when trying to extract code from a microbit where we have lost the source.

>  ~/ Downloads/ubittool-0.6.0-mac-cli read-code 
> Executing: Extract the MicroPython code to a file or print it.
> 
> MicroPython code will be output to console.
> Reading the micro:bit flash contents...
> Traceback (most recent call last):
>   File "ubittool/cmds.py", line 164, in read_python_code
>   File "uflash.py", line 200, in extract_script
>   File "uflash.py", line 128, in unhexlify
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 1: invalid start byte
> 
> ----------------------------------------------------------------------
> Error: Could not decode the MicroPython code from flash
>  ~/

 
I have attached the output of the read-flash command for reference.

[DETAILS.TXT](https://github.com/carlosperate/ubittool/files/7822296/DETAILS.TXT)
[read-flash-output.txt.gz](https://github.com/carlosperate/ubittool/files/7822320/read-flash-output.txt.gz)

**Comment by carlosperate** [comment]
Hi @kingsfleet,
Was this a MakeCode or Python programme?
Unfortunately that feature only works for very old Python programmes.

**Comment by kingsfleet** [comment]
This was with MakeCode using blocks unfortunately it glitched and lost the undo buffer loosing #1 son's Christmas light project. I was hoping to get the code back out. Is there anything useful in the hex dump that I can use?

**Comment by carlosperate** [comment]
Unfortunately not, sorry, if it was done in a recent version of MakeCode (from the last year or so) then the metadata with the code is no longer stored in flash.
MakeCode can have several projects saved in the browser, is it worth a look to see if an old project there might be the one you lost, and if you have an old hex file with that project in your downloads folder you can still load it back into the editor.
