### ISSUE TITLE
Executable CLI does not include tkinter

### ISSUE THREAD

**Issue by carlosperate** [carlosperate/ubittool#9]
So we should either not show the command or show an error message that explains the situation.

```
$ ./ubittool-cli gui
Traceback (most recent call last):
  File "ubittool/cli.py", line 158, in <module>
  File "ubittool/cli.py", line 154, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "ubittool/cli.py", line 147, in gui
  File "/Users/travis/.local/share/virtualenvs/ubittool-PRs-Fujz/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "ubittool/gui.py", line 7, in <module>
ModuleNotFoundError: No module named 'tkinter'
[73676] Failed to execute script cli
```

**Comment by carlosperate** [comment]
Or perhaps hide the command when running from the self-contained executable?
